version: '3.1'

services:

  php:
    build: 
      context: php
      dockerfile: ./Dockerfile
    volumes:
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./htdocs:/var/www/html
    ports:
      - 8000:80
    restart: always
    container_name: docker-apache-php
      
  mysql:
    build:
      context: mysql
      dockerfile: ./Dockerfile
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    container_name: docker-apache-mysql
     
  phpmyadmin:
    image: phpmyadmin
    volumes:
      - ./phpmyadmin/sessions:/sessions
    ports:
      - 9000:80
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    container_name: docker-apache-phpmyadmin