####################################
# DESCRIPTION: Dockerfile for PHP
# CONTAINER: PHP
# OWNER: RenGoto
####################################
FROM php:7.2-apache
MAINTAINER "Ren Goto" <r0719en@pluslab.org>

RUN apt-get update \
    && docker-php-ext-install pdo_mysql